/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-orange': '#ea8d28',
        'primary-dark-blue': '#144b8c',
        'primary-light-blue': '#3ca9d6',
        'light-gray': '#f2f2f2',
        'lighter-gray': '#f9f9f9',
        'medium-gray': '#6f6f6f',
        'dark-gray': '#434343',
        'divider-gray': '#bababa',
      },
      fontFamily: {
        heading: ['Josefin Sans', 'sans-serif'],
        body: ['Mulish', 'sans-serif'],
        josefin: ['Josefin Sans', 'sans-serif'],
        mulish: ['Mulish', 'sans-serif'],
        source: ['Source Sans 3', 'sans-serif'],
      },
      fontSize: {
        'xs': '12px',
        'sm': '14px',
        'base': '16px',
        'lg': '20px',
        'xl': '28px',
        '2xl': '36px',
        '3xl': '42px',
        '4xl': '48px',
      },
      spacing: {
        'xs': '4px',
        'sm': '6px',
        'md': '10px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '30px',
        '3xl': '60px',
      },
      borderRadius: {
        'sm': '6px',
        'md': '16px',
        'lg': '20px',
        'xl': '30px',
        '2xl': '40px',
        '3xl': '60px',
        '4xl': '90px',
      },
      boxShadow: {
        'sm': '0px 4px 6px rgba(0, 0, 0, 0.05)',
        'md': '0px 4px 10px rgba(0, 0, 0, 0.10)',
        'lg': '0px 4px 30px rgba(0, 0, 0, 0.10)',
        'xl': '0px 4px 40px rgba(4, 29, 77, 0.07)',
        'header': '0px 4px 10px rgba(0, 0, 0, 0.30)',
      },
      screens: {
        'xs': '375px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1200px',
        '2xl': '1440px',
        '3xl': '1920px',
      },
    },
  },
  plugins: [],
}